# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x03rpc\"j\n\x11GenerationRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nmax_length\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\r\n\x05top_p\x18\x04 \x01(\x02\x12\r\n\x05top_k\x18\x05 \x01(\x05\"M\n\x0fGenerationChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12)\n\x08metadata\x18\x02 \x03(\x0b\x32\x17.rpc.GenerationMetadata\"P\n\x12GenerationResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12)\n\x08metadata\x18\x02 \x03(\x0b\x32\x17.rpc.GenerationMetadata\"1\n\x12GenerationMetadata\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\x96\x01\n\x11GenerationService\x12=\n\nGeneration\x12\x16.rpc.GenerationRequest\x1a\x17.rpc.GenerationResponse\x12\x42\n\x10GenerationStream\x12\x16.rpc.GenerationRequest\x1a\x14.rpc.GenerationChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATIONREQUEST']._serialized_start=22
  _globals['_GENERATIONREQUEST']._serialized_end=128
  _globals['_GENERATIONCHUNK']._serialized_start=130
  _globals['_GENERATIONCHUNK']._serialized_end=207
  _globals['_GENERATIONRESPONSE']._serialized_start=209
  _globals['_GENERATIONRESPONSE']._serialized_end=289
  _globals['_GENERATIONMETADATA']._serialized_start=291
  _globals['_GENERATIONMETADATA']._serialized_end=340
  _globals['_GENERATIONSERVICE']._serialized_start=343
  _globals['_GENERATIONSERVICE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
